# ============================================
# NOVEL ASSISTANT PROJECT SETUP SCRIPT
# Creates folder, subfolders, placeholder files,
# initializes Git, and opens in VS Code
# ============================================

Write-Host "📁 Creating Novel Assistant project structure..." -ForegroundColor Cyan

# Root project folder
$projectRoot = "$env:USERPROFILE\novel-assistant"

# Create root directory
New-Item -ItemType Directory -Force -Path $projectRoot | Out-Null

# Subfolders
$subfolders = @(
    "specs",
    "agent",
    "agent/tools",
    "agent/prompts",
    "examples"
)

foreach ($folder in $subfolders) {
    New-Item -ItemType Directory -Force -Path "$projectRoot\$folder" | Out-Null
}

Write-Host "📂 Folders created."

# ================================
# Create placeholder files
# ================================

# File templates
$files = @{
    "README.md" = "# Novel Assistant Project`nA structured AI-assisted system for writing novels, outlines, and chapters."

    "specs/NOVEL_ASSISTANT_MASTER_SPEC.md" = "# Novel Assistant Master Specification`n*(Content will be inserted by ChatGPT and refined with Copilot)*"
    "specs/SYSTEM_PROMPT.md" = "# System Prompt`n*(To be generated by ChatGPT)*"
    "specs/TOKEN_STRATEGY.md" = "# Token Strategy`n*(Will outline token-saving workflow)*"
    "specs/WORKFLOW_PIPELINE.md" = "# Workflow Pipeline`n*(Defines full writing pipeline)*"

    "agent/agent_core.md" = "# Agent Core`n*(Placeholder — actual logic will be added later)*"

    "examples/sample_outline.md" = "# Sample Outline`n*(Placeholder example)*"
    "examples/sample_scene.md" = "# Sample Scene`n*(Placeholder example)*"
    "examples/sample_chapter.md" = "# Sample Chapter`n*(Placeholder)*"

    ".gitignore" = @"
# Ignore Python caches
__pycache__/
*.pyc

# Node modules (if JS used later)
node_modules/

# Environment files
.env
.env.local
.env.*.local

# VS Code settings backups
.vscode/

# System files
Thumbs.db
.DS_Store
"@
}

# Write files
foreach ($file in $files.GetEnumerator()) {
    $filePath = "$projectRoot\$($file.Key)"
    $file.Value | Out-File -FilePath $filePath -Encoding utf8
}

Write-Host "📝 Placeholder files created."

# ================================
# Initialize Git repository
# ================================

Set-Location -Path $projectRoot

git init | Out-Null
git add . | Out-Null
git commit -m "Initial project structure" | Out-Null

Write-Host "🐙 Git repository initialized."

# ================================
# Open in VS Code
# ================================

Write-Host "🚀 Opening project in VS Code..."
code $projectRoot

Write-Host "🎉 Project setup complete!" -ForegroundColor Green
