// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbdbhelhvefrhcdbicss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmb3JocHFqcW1maGVvb3Bqa2NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyOTU3ODIsImV4cCI6MjA1Mzg3MTc4Mn0.okacqHVR_u-2zV6tuV-VaK_mei1OXaCqKa3AequAURs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);